jenkins_plugin:
  - javax-activation-api
  - javax-mail-api
  - cloudbees-folder
  - mina-sshd-api-common
  - mina-sshd-api-core
  - sshd
  - antisamy-markup-formatter
  - structs
  - token-macro
  - build-timeout
  - credentials
  - trilead-api
  - ssh-credentials
  - workflow-step-api
  - plain-credentials
  - credentials-binding
  - scm-api
  - workflow-api
  - timestamper
  - caffeine-api
  - script-security
  - jaxb
  - snakeyaml-api
  - jackson2-api
  - plugin-util-api
  - font-awesome-api
  - bootstrap5-api
  - jquery3-api
  - echarts-api
  - display-url-api
  - workflow-support
  - checks-api
  - junit
  - matrix-project
  - resource-disposer
  - ws-cleanup
  - ant
  - durable-task
  - workflow-durable-task-step
  - jdk-tool
  - command-launcher
  - bouncycastle-api
  - workflow-scm-step
  - workflow-cps
  - workflow-job
  - jakarta-activation-api
  - jakarta-mail-api
  - apache-httpcomponents-client-4-api
  - mailer
  - workflow-basic-steps
  - gradle
  - pipeline-milestone-step
  - pipeline-build-step
  - variant
  - pipeline-groovy-lib
  - pipeline-stage-step
  - pipeline-model-api
  - pipeline-model-extensions
  - branch-api
  - workflow-multibranch
  - pipeline-stage-tags-metadata
  - jsch
  - git-client
  - pipeline-input-step
  - pipeline-model-definition
  - workflow-aggregator
  - jjwt-api
  - okhttp-api
  - github-api
  - git
  - github
  - github-branch-source
  - pipeline-github-lib
  - pipeline-graph-analysis
  - pipeline-rest-api
  - pipeline-stage-view
  - ssh-slaves
  - matrix-auth
  - pam-auth
  - ldap
  - email-ext
  - google-oauth-plugin
  - job-dsl
  - git-server
  - authentication-tokens
  - lockable-resources
  - jenkins-design-language
  - uno-choice
  - google-login
  - role-strategy
  - oauth-credentials
  - generic-webhook-trigger
  - slack
  - kubernetes
  - http_request

users:
  - username: learning
    state: present
    groups: google-sudoers
    ssh_public_key:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCPgrE4uCK4zVosgnJ+ru0JANC6FcXWQcbn3uwzZXokhLZODehxgSaUVk0RppjvE7th7dq9ZLWCvpcxJQ/rWwPk= learning@thinkbook

pg_version: 13
pg_repo_version: jammy