### jenkins - start ###

jenkins_plugin:
  - javax-activation-api
  - javax-mail-api
  - cloudbees-folder
  - mina-sshd-api-common
  - mina-sshd-api-core
  - sshd
  - antisamy-markup-formatter
  - structs
  - token-macro
  - build-timeout
  - credentials
  - trilead-api
  - ssh-credentials
  - workflow-step-api
  - plain-credentials
  - credentials-binding
  - scm-api
  - workflow-api
  - timestamper
  - caffeine-api
  - script-security
  - jaxb
  - snakeyaml-api
  - jackson2-api
  - plugin-util-api
  - font-awesome-api
  - bootstrap5-api
  - jquery3-api
  - echarts-api
  - display-url-api
  - workflow-support
  - checks-api
  - junit
  - matrix-project
  - resource-disposer
  - ws-cleanup
  - ant
  - durable-task
  - workflow-durable-task-step
  - jdk-tool
  - command-launcher
  - bouncycastle-api
  - workflow-scm-step
  - workflow-cps
  - workflow-job
  - jakarta-activation-api
  - jakarta-mail-api
  - apache-httpcomponents-client-4-api
  - mailer
  - workflow-basic-steps
  - gradle
  - pipeline-milestone-step
  - pipeline-build-step
  - variant
  - pipeline-groovy-lib
  - pipeline-stage-step
  - pipeline-model-api
  - pipeline-model-extensions
  - branch-api
  - workflow-multibranch
  - pipeline-stage-tags-metadata
  - jsch
  - git-client
  - pipeline-input-step
  - pipeline-model-definition
  - workflow-aggregator
  - jjwt-api
  - okhttp-api
  - github-api
  - git
  - github
  - github-branch-source
  - pipeline-github-lib
  - pipeline-graph-analysis
  - pipeline-rest-api
  - pipeline-stage-view
  - ssh-slaves
  - matrix-auth
  - pam-auth
  - ldap
  - email-ext
  - google-oauth-plugin
  - job-dsl
  - git-server
  - authentication-tokens
  - lockable-resources
  - jenkins-design-language
  - uno-choice
  - google-login
  - role-strategy
  - oauth-credentials
  - generic-webhook-trigger
  - slack
  - kubernetes
  - http_request

### jenkins - end ###

### postgresql - start ###
users:
  - username: learning
    state: present
    groups: google-sudoers
    ssh_public_key:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCPgrE4uCK4zVosgnJ+ru0JANC6FcXWQcbn3uwzZXokhLZODehxgSaUVk0RppjvE7th7dq9ZLWCvpcxJQ/rWwPk= learning@thinkbook

pg_version: 13
pg_repo_version: jammy
### postgresql - end ###

### elasticsearch - start ###
elasticsearch_jvm_xms: 512m
elasticsearch_jvm_xmx: 512m
### elasticsearch - end ###

### opensearch - start ###

## Common opensearch configuration parameters ##
os_cluster_name: development-cluster

# opensearch download
os_download_url: https://artifacts.opensearch.org/releases/bundle/opensearch

# opensearch version
# 2.x Latest Version
os_version: "2.9.0"

# opensearch dashboards version
# 2.x Latest Version
os_dashboards_version: "2.9.0"

# Configure hostnames for opensearch nodes
# It is required to configure SSL
# Example es1.example.com, es2.example.com
domain_name: example.com

# Java memory heap values(GB) for opensearch
# You can change it based on server specs
xms_value: 2
xmx_value: 2

# Cluster type whether its single-node or multi-node
cluster_type: multi-node

# opensearch user info
os_user: opensearch

os_dashboards_user: opensearch-dashboards

# Number of days that certificates are valid
cert_valid_days: 730

# Auth type: 'internal' or 'oidc' (OpenID). Default: internal
auth_type: internal

# OIDC settings
oidc:
  description: "Authenticate via IdP"
  # OpenID server URI
  connect_url: https://oidc.example.com/auth/realms/<realm name>/.well-known/openid-configuration
  # The JWT token field that contains the user name
  subject_key: preferred_username
  # the JWT token field that contains a list of user roles
  roles_key: roles
  # Scopes
  scopes: "openid profile email"
  # The address of Dashboards to redirect the user to after successful authentication
  dashboards_url: http(s)://<dashboards address>.example.com
  # IdP client ID
  client_id: opensearch
  # IdP client secret
  client_secret: "00000000-0000-0000-0000-000000000000"

# Overwrite demo configurations with your own
copy_custom_security_configs: false

# To override demo configurations, you can use your own configuration files.
# Place them in the "files" directory. Specify the path to the files
custom_security_plugin_configs:
  - ../../../roles/opensearch/files/tenants.yml
  - ../../../roles/opensearch/files/roles.yml
  - ../../../roles/opensearch/files/roles_mapping.yml
  - ../../../roles/opensearch/files/internal_users.yml

iac_enable: false
### opensearch - end ###