---
- name: PHP Installation
  hosts: "{{ HOSTS | default([])}}"
  gather_facts: false
  become: true

  tasks:
    - name: Installing Remi Repository
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: Installing php
      yum:
        enablerepo: "remi,remi-php74" # --> "remi,remi-php74" or "remi,remi-php80"
        name:
        - php
        - php-common
        - php-cli
        - php-gd
        - php-curl
        - php-mysqlnd
        - php-fpm
        - php-mysqli
        - php-json
        - php-cgi
        - php-xsl
        - php-gd
        - php-mbstring
        - php-zip
        - php-xmlrpc
        - php-soap
        - php-intl
        - php-exif
        - php-pcntl
        - php-bcmath
        - php-opcache
        state: latest
