---

- name: Add an Apt signing key mongodb
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
  tags: install

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A
  tags: install

- name: Add mongodb repository
  ansible.builtin.apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
    state: present
    filename: /etc/apt/sources.list.d/mongodb-org-5.0.list
  tags: install

- name: Install dependency mongodb in ubuntu 22.04
  apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  tags: install    

- name: Add pritunl repository
  ansible.builtin.apt_repository:
    repo: deb http://repo.pritunl.com/stable/apt jammy main
    state: present
    filename: /etc/apt/sources.list.d/pritunl.list
  tags: install

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  tags: install

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
  tags: install

- name: Install dependencies and pre-requisite pritunl
  apt:
    update_cache: yes
    name:
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - pritunl
      - mongodb-org
    state: present
  tags: install

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
  tags: install

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  tags: install

- name: Start and enabled Pritunl Services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - pritunl
    - mongod
  tags: install

- name: get setup key
  shell: pritunl setup-key
  register: setup
  tags: install

- debug:
    msg: "SETUP KEY: {{ setup.stdout_lines }}"
  tags: install

- name: Pritunl setup instructions
  debug:
    msg: |
      - If you already had SETUP KEY, please accessing pritunl web admin https://[PRITUNL-PUBLIC-IP]
      - enter your generated SETUP KEY to Pritunl Database Setup Page, klik Save
      - It will show Database Upgrade process, after that it's show Pritunl Login Page
      - Run ansible-playbook again with tags: config to get default-password and user.
  tags: install