---

- name: Add fqdn hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"
  become: yes

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Jakarta