---

- name: Add fqdn hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"
  become: true

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Jakarta

- name: install important packages
  vars:
    ansible_python_interpreter: /usr/bin/python
  package:
    name:
      - htop
      - tmux
      - vim
      - curl
      - python3
      - python3-setuptools
      - python3-pip
    state: present